[package]

name = "hematite_server"
version = "0.0.1"
authors = [
    "Fenhl <fenhl@fenhl.net>",
    "Carlos Cobo <toqueteos@gmail.com>"
]

[[bin]]
name = "hematite_server"
path = "server/main.rs"

[lib]
name = "hematite_server"
path = "src/lib.rs"

[dependencies]
byteorder = "*"
uuid = "*"
flate2 = "*"
